Unittesting - part 1
eastgenomics/trendyQC pull request #68
Opened 2024-02-19 11:24 UTC by Yu-jinKim

- Renamed the test script (which is why it's a whole new file)
- Make L002 fastqc data optional in the Fastqc table

List of tests:
- Check if the content gathered for the MultiQC object is appropriate depending on the assay
- Check if the MultiQC object is importable
    - It is already in the db
    - It is not in the db
    - The assay key has been deleted
- Check if the assay key is in the config assay
- Check if the fastqc data has been imported correctly

```
root@9a487de7928c:/app# python trendyqc/manage.py test trend_monitoring.tests
Found 7 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
DNAnexus login successful
.......
----------------------------------------------------------------------
Ran 7 tests in 91.128s

OK
Destroying test database for alias 'default'...
```

2024-02-19 11:24 UTC, pep8speaks commented
Hello @Yu-jinKim! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`trendyqc/trend_monitoring/models/fastq_qc.py`](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/models/fastq_qc.py):

> [Line 7:80](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/models/fastq_qc.py#L7): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (141 > 79 characters)
> [Line 8:80](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/models/fastq_qc.py#L8): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (141 > 79 characters)



* In the file [`trendyqc/trend_monitoring/tests/test_multiqc.py`](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/tests/test_multiqc.py):

> [Line 39:80](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/tests/test_multiqc.py#L39): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 51:80](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/tests/test_multiqc.py#L51): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 62:80](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/tests/test_multiqc.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 138:39](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/tests/test_multiqc.py#L138): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 149:80](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/tests/test_multiqc.py#L149): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 177:80](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/tests/test_multiqc.py#L177): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 201:35](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/tests/test_multiqc.py#L201): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 293:80](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/tests/test_multiqc.py#L293): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)
> [Line 317:80](https://github.com/eastgenomics/trendyQC/blob/818e0c0fe46247582c2d25ccd571322734d38f93/trendyqc/trend_monitoring/tests/test_multiqc.py#L317): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)

2024-02-20 09:22 UTC, jethror1 requested changes
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/68)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @Yu-jinKim)

___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 6 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4mGFBCBxYCaKY5MgY:-Nr4mGFBCBxYCaKY5MgZ:bogs7jj) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L6)):*
> ```Python
> 
> from django.test import TestCase
> import regex
> ```

why use regex over re?



_Code quote:_
```Python
import regex
```
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 76 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4mj7rAa4yiIPyePoy:-Nr4mj7rAa4yiIPyePoz:b-adrftw) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L76)):*
> ```Python
> 
>     @classmethod
>     def untar_stream_reports(cls, tar):
> ```

I assume this is a fairly expensive function to run and why your tests take a while, since using `setUp` calls this every time, I would consider not using `setUp` and having this just in the outer scope (aslong as you're not changing it such as adding content), then it is only called once the class of tests running (I should probably look up whats best practice for this and ensuring you don't modify it and have tests affecting each other)



_Code quote:_
```Python
def untar_stream_reports(cls, tar):
```
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 102 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4nn2K1vBifSZQt6mX:-Nr4nn2K1vBifSZQt6mY:b4ngbfl) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L102)):*
> ```Python
>             # should probably be another function
>             # looping through the assays and the files
>             for assay, files in tar_dict.items():
> ```

why 2 loops here? can't this be in the above?
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 148 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4nuv67VsWAMYqSo7-:-Nr4nuv67VsWAMYqSo70:bk1pmei) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L148)):*
> ```Python
> 
>     @classmethod
>     def import_tool_info(cls):
> ```

missing docstring



_Code quote:_
```Python
def import_tool_info(cls):
```
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 157 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4o2fY-mp2VZlXqZby:-Nr4o2fY-mp2VZlXqZbz:b-wmu8yo) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L157)):*
> ```Python
> 
>     @classmethod
>     def setUpClass(cls):
> ```

again, not sure if you want to do all of these for every test, but happy to be persuaded otherwise



_Code quote:_
```Python
def setUpClass(cls):
```
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 314 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4oUZP5DXN6jEm5QjI:-Nr4oUZQ1XXAIMaaJDCJ:buoszvk) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L314)):*
> ```Python
>                     read = match.groupdict()["read"]
>                 else:
>                     exit()
> ```

 why exit here?



_Code quote:_
```Python
 exit()
```


<!-- Sent from Reviewable.io -->

2024-02-20 09:55 UTC, Yu-jinKim reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/68)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @jethror1)

___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 6 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4mGFBCBxYCaKY5MgY:-Nr4sGnV-PQVZN6VAy4W:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L6)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why use regex over re?
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 76 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4mj7rAa4yiIPyePoy:-Nr4s30U2MNEvI0vmCQ6:b-4pvkjf) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L76)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I assume this is a fairly expensive function to run and why your tests take a while, since using `setUp` calls this every time, I would consider not using `setUp` and having this just in the outer scope (aslong as you're not changing it such as adding content), then it is only called once the class of tests running (I should probably look up whats best practice for this and ensuring you don't modify it and have tests affecting each other)
</blockquote></details>

Replied below
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 102 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4nn2K1vBifSZQt6mX:-Nr4vxMCCZZEpQd-Oftz:b-q992uc) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L102)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why 2 loops here? can't this be in the above?
</blockquote></details>

I think i was lazy and brain starved, Done.
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 148 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4nuv67VsWAMYqSo7-:-Nr4r_-w-hfyXAoycY3K:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L148)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

missing docstring
</blockquote></details>

Done.
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 157 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4o2fY-mp2VZlXqZby:-Nr4qnP94-JHeSXTFUn1:befhx0w) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L157)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

again, not sure if you want to do all of these for every test, but happy to be persuaded otherwise
</blockquote></details>

it is not called every time. SetUpClass is executed only once before the battery of tests unlike SetUp, example here:
```
    @classmethod
    def setUpClass(cls):
        """ Set up the data for the battery of tests by:
        - Logging into dnanexus
        - Getting the test tar and performing some checks
        - Untar-ing the reports
        - Importing said reports
        """
        print("blarg")
        super(TestMultiqc, cls).setUpClass()
        login_to_dnanexus()
        cls.tool_data = cls.import_tool_info()
        reports_tar = cls.get_reports_tar()
        cls.reports = cls.untar_stream_reports(reports_tar)
        cls.multiqc_objects = cls.import_test_reports(cls.reports)
```

```
root@77633a405833:/app# python trendyqc/manage.py test trend_monitoring.tests
Found 7 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
blarg
DNAnexus login successful
.......
----------------------------------------------------------------------
Ran 7 tests in 32.367s

OK
Destroying test database for alias 'default'...
```

other example on stackoverflow: https://stackoverflow.com/a/23670844/9704855
___
*[`trendyqc/trend_monitoring/tests/test_multiqc.py` line 314 at r2](https://reviewable.io/reviews/eastgenomics/trendyQC/68#-Nr4oUZP5DXN6jEm5QjI:-Nr4sXqG1jUcYZK3vcbV:b-896fix) ([raw file](https://github.com/eastgenomics/trendyQC/blob/4e7791d8f7f57853d2e344cd0db4ee22b841643c/trendyqc/trend_monitoring/tests/test_multiqc.py#L314)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why exit here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-20 10:39 UTC, jethror1 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/trendyQC/68)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2024-02-20 10:40 UTC, merged